---
- hosts: localhost
  tasks:

    - ec2_vpc_net_info:
      register: vpc_info

    - name: Display vpc info
      debug:
        var: vpc_info

    # - name: create a VPC with a couple of tags
    #   ec2_vpc_net:
    #     name: kubernetes2
    #     cidr_block: 10.10.0.0/16
    #     region: us-east-1
    #     state: absent
    #     tags:
    #       module: ec2_vpc_net
    #       this: works
    #     tenancy: default
    #   register: vpc